[package]
name = "greyer"
version = "0.1.0"
edition = "2021"

[dependencies]
srtlib = "0.2.0"
regex = "1.11.1"
ffmpeg-sidecar = { version = "=2.0.0" }
clap = { version = "4.5.26", features = ["derive"] }
tl = "0.7.8"

#openssl = { version = "0.10.70", features = ["vendored"] }
