[package]
name = "greyer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
srtlib = "0.2.0"
palette = "0.7.6"
regex = "1.11.1"
time = "0.3.37"
ffmpeg-the-third= "3.0.0"
